const cors = require('cors')
const express = require('express')
const rateLimit = require('express-rate-limit')
const helmet = require('helmet')
const morgan = require('morgan')
const env = require('./config/env')
const healthRouter = require('./routes/health.routes')
const authRouter = require('./routes/auth.routes')
const adminRouter = require('./routes/admin.routes')
const restaurantRouter = require('./routes/restaurant.routes')
const ngoRouter = require('./routes/ngo.routes')
const recyclerRouter = require('./routes/recycler.routes')
const { errorHandler, notFoundHandler } = require('./middlewares/errorHandler')

const app = express()

app.disable('x-powered-by')
app.use(helmet())
app.use(cors({ origin: env.CLIENT_URL, credentials: true }))
app.use(express.json({ limit: '1mb' }))
app.use(express.urlencoded({ extended: true, limit: '1mb' }))
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'))
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }))

app.use('/health', healthRouter)
app.use('/api/v1/auth', authRouter)
app.use('/api/v1/admin', adminRouter)
app.use('/api/v1/restaurant', restaurantRouter)
app.use('/api/v1/ngo', ngoRouter)
app.use('/api/v1/recycler', recyclerRouter)
app.use(notFoundHandler)
app.use(errorHandler)

module.exports = app

